name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.12.0
        with:
          toolchain: stable
          cache: true

      - name: Run tests
        run: cargo test
